# Generated by Django 5.0.9 on 2024-11-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cc_num", models.IntegerField()),
                ("merchant", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("lat", models.DecimalField(decimal_places=7, max_digits=10)),
                ("long", models.DecimalField(decimal_places=7, max_digits=10)),
                ("transaction_num", models.CharField(max_length=25)),
                ("merch_lat", models.DecimalField(decimal_places=7, max_digits=10)),
                ("merch_long", models.DecimalField(decimal_places=7, max_digits=10)),
                ("is_fraud", models.BooleanField()),
                ("transaction_date", models.DateTimeField()),
                ("transaction_time", models.TimeField()),
                ("amt_ratio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("daily_transaction_count", models.IntegerField()),
                (
                    "user_location_distance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
    ]
